# Generated by Django 4.2.5 on 2023-09-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_profile_is_police_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policeofficer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_police_officer',
        ),
    ]
