# Generated by Django 4.2.5 on 2023-09-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_policeofficer_email_policeofficer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
