# Generated by Django 4.2.5 on 2023-09-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_complaint_solved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='solved_by',
        ),
    ]
