# Generated by Django 4.2.5 on 2023-09-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_remove_complaint_solved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('robbery', 'Robbery'), ('assault', 'Assault'), ('fraud', 'Fraud'), ('murder', 'Murder'), ('burglary', 'Burglary'), ('abuse', 'Abuse'), ('kidnapping', 'Kidnapping'), ('cybercrime', 'Cyber Crime'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
