# Generated by Django 4.2.5 on 2023-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_missingperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='complaint',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
