# Generated by Django 4.2.5 on 2023-11-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_remove_missingperson_complaint_missingperson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='missing_person_photo',
            field=models.ImageField(blank=True, null=True, upload_to='missing_person_photo/'),
        ),
    ]
