# Generated by Django 4.2.5 on 2023-11-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_missingperson_missing_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
